-- src/main/resources/schema.sql

-- Table for Cliente
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    telefone VARCHAR(255),
    endereco VARCHAR(255),
    ativo BOOLEAN NOT NULL
);

-- Table for Restaurante
CREATE TABLE restaurante (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    cnpj VARCHAR(255),
    endereco VARCHAR(255),
    ativo BOOLEAN NOT NULL,
    avaliacao DOUBLE,
    taxa_entrega DOUBLE,
    categoria VARCHAR(255),
    telefone VARCHAR(255)
);

-- Table for Produto
CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    preco DOUBLE NOT NULL,
    restaurante_id BIGINT,
    ATIVO BOOLEAN NOT NULL,
    disponivel BOOLEAN NOT NULL,
    categoria VARCHAR(255),
    FOREIGN KEY (restaurante_id) REFERENCES restaurante(id)
);

-- Table for Pedido
CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_pedido TIMESTAMP,
    status VARCHAR(50),
    subtotal DOUBLE NOT NULL,
    taxa_entrega DOUBLE NOT NULL,
    valor_total DOUBLE NOT NULL,
    cliente_id BIGINT,
    restaurante_id BIGINT,
    endereco_entrega VARCHAR(255),
    observacoes VARCHAR(255),
    numero_pedido VARCHAR(50) UNIQUE,
    FOREIGN KEY (cliente_id) REFERENCES cliente(id),
    FOREIGN KEY (restaurante_id) REFERENCES restaurante(id)
);

-- Table for Item_Pedido (Add this block)
CREATE TABLE item_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Assuming a primary key for item_pedido
    pedido_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INT NOT NULL,
    preco_unitario DOUBLE NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES pedido(id),
    FOREIGN KEY (produto_id) REFERENCES produto(id)
);